### ISSUE TITLE
Bug Report: AuroraText Overlay Issue in Magic UI

### ISSUE THREAD

**Issue by dev25-hs** [magicuidesign/magicui#570]
When importing and using the AuroraText component from Magic UI, the color shift effect does not apply correctly inside the text. Instead, it appears as if a div with changing colors is placed over the text, rather than blending seamlessly with the text itself.

**To Reproduce**
Steps to reproduce the issue:

Install and import AuroraText from Magic UI.
Use the component in a Next.js/React project with the following sample code:

```
import { AuroraText } from "magic-ui";

export default function Example() {
  return  <h1 className="text-4xl font-bold tracking-tighter md:text-5xl lg:text-7xl">
      <AuroraText>Free Trial</AuroraText> classes for 3 days
    </h1>
}
```
Run the application and observe the text rendering.

**Expected Behavior**
The color shifting effect should be applied inside the text itself, rather than appearing as an overlay outside of the text boundaries.

**Screenshots**
Attached is an image showing the issue where the gradient effect is appearing as a separate overlay instead of affecting the text properly.
![Image](https://github.com/user-attachments/assets/eb260112-dec8-4c0f-bf51-c3fed9af394d)

This issue may be related to improper styling or missing blending properties in the component. If there's a workaround (such as additional CSS or props to modify the effect), please advise.

**Comment by SikandarJODD** [comment]
try adding inside animations in tailwind.config.ts 
```
aurora: "aurora 60s linear infinite",
```

**Comment by SikandarJODD** [comment]
you can try adding below code inside  tailwind.config.ts 

```ts
 plugins: [
    addVariablesForColors,
    function ({ matchUtilities, theme }: any) {
      matchUtilities(
        {
          "bg-grid": (value: any) => ({
            backgroundImage: `url("${svgToDataUri(
              `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32" width="32" height="32" fill="none" stroke="${value}"><path d="M0 .5H31.5V32"/></svg>`
            )}")`,
          }),
          "bg-grid-small": (value: any) => ({
            backgroundImage: `url("${svgToDataUri(
              `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32" width="8" height="8" fill="none" stroke="${value}"><path d="M0 .5H31.5V32"/></svg>`
            )}")`,
          }),
          "bg-dot": (value: any) => ({
            backgroundImage: `url("${svgToDataUri(
              `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32" width="16" height="16" fill="none"><circle fill="${value}" id="pattern-circle" cx="10" cy="10" r="1.6257413380501518"></circle></svg>`
            )}")`,
          }),
        },
        { values: flattenColorPalette(theme("backgroundColor")), type: "color" }
      );
    }
  ],
```

```ts
// This plugin adds each Tailwind color as a global CSS variable, e.g. var(--gray-200).
function addVariablesForColors({ addBase, theme }: any) {
  let allColors = flattenColorPalette(theme("colors"));
  let newVars = Object.fromEntries(
    Object.entries(allColors).map(([key, val]) => [`--${key}`, val])
  );

  addBase({
    ":root": newVars,
  });
}
```

**Comment by DaniloTrotta** [comment]
> --color-1: 0 100% 63%;
>     --color-2: 270 100% 63%;
>     --color-3: 210 100% 63%;
>     --color-4: 195 100% 63%;
>     --color-5: 90 100% 63%;

I have the same problem and this doesn't fix it for me

**Comment by SikandarJODD** [comment]
hey did you install shadcn i don't how when i do same thing - by installing shadcn - it works - i am still confuse how does it work

**Comment by SikandarJODD** [comment]
@DaniloTrotta  @WasiHaiderHS 
check this out : Now i debug this issue it was about adding bg-background in body 


```css
@tailwind base;
@tailwind components;
@tailwind utilities;

@layer base {
  :root {
    --background: 0 0% 100%;
    --color-1: 0 100% 63%;
    --color-2: 270 100% 63%;
    --color-3: 210 100% 63%;
    --color-4: 195 100% 63%;
    --color-5: 90 100% 63%;
  }
}

@layer base {
  body {
    @apply bg-background ;
  }
}
```

here is my tailwind.config.ts file

```ts
import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: ["class"],
  content: ["./src/**/*.{html,js,svelte,ts}"],
  safelist: ["dark"],
  theme: {
    extend: {
      colors: {
        "color-1": "hsl(var(--color-1))",
        "color-2": "hsl(var(--color-2))",
        "color-3": "hsl(var(--color-3))",
        "color-4": "hsl(var(--color-4))",
        "color-5": "hsl(var(--color-5))",
        background: "hsl(var(--background) / <alpha-value>)",
      },
      keyframes: {
        "aurora-border": {
          "0%, 100%": { borderRadius: "37% 29% 27% 27% / 28% 25% 41% 37%" },
          "25%": { borderRadius: "47% 29% 39% 49% / 61% 19% 66% 26%" },
          "50%": { borderRadius: "57% 23% 47% 72% / 63% 17% 66% 33%" },
          "75%": { borderRadius: "28% 49% 29% 100% / 93% 20% 64% 25%" },
        },
        "aurora-1": {
          "0%, 100%": { top: "0", right: "0" },
          "50%": { top: "50%", right: "25%" },
          "75%": { top: "25%", right: "50%" },
        },
        "aurora-2": {
          "0%, 100%": { top: "0", left: "0" },
          "60%": { top: "75%", left: "25%" },
          "85%": { top: "50%", left: "50%" },
        },
        "aurora-3": {
          "0%, 100%": { bottom: "0", left: "0" },
          "40%": { bottom: "50%", left: "25%" },
          "65%": { bottom: "25%", left: "50%" },
        },
        "aurora-4": {
          "0%, 100%": { bottom: "0", right: "0" },
          "50%": { bottom: "25%", right: "40%" },
          "90%": { bottom: "50%", right: "25%" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "caret-blink": "caret-blink 1.25s ease-out infinite",
      },
    },
  },
};

export default config;

```
well guys above it for svelte - this might be somewhat diff for react projects - i hope you get the idea 
we need to add ``` background: "hsl(var(--background) / <alpha-value>)",```

**Comment by 1chooo** [comment]
I have the same issue when using in Safari

please visit https://stonix.1chooo.com to see the bug

<img width="1280" alt="Image" src="https://github.com/user-attachments/assets/43928bb1-1feb-445d-bd79-2dcb219beecd" />

**Comment by dillionverma** [comment]
Hi! Can you please try the latest version of aurora text? We just merged in #580 which aims to address these issues :)

**Comment by 1chooo** [comment]
@dillionverma 

There is still the same issue in Safari, but it works in Chrome. Could you help me fix it?

<img width="1392" alt="Image" src="https://github.com/user-attachments/assets/0149f037-d72e-424f-8b8a-e4a5d0f4b513" />

**Comment by dillionverma** [comment]
Try on safari now! Updated the latest version @1chooo

**Comment by 1chooo** [comment]
Hi @dillionverma ! Sorry for the late replying. It's still not work; however, it will show up immediately when refreshing the website with Safari.

https://github.com/user-attachments/assets/ca885632-60c0-41ad-a53a-efd8677c0be1

**Comment by dillionverma** [comment]
Hi all! Thanks for reporting this.

We re-did the component again recently with a much simpler implementation and cross-browser support!

Feel free to try the latest version on the site and let me know if you have any feedback :)

Will close issue for now

https://magicui.design/docs/components/aurora-text
